### PR TITLE
Fix executable jar not working

### LINKED ISSUE #21: The app does not run with java -jar
## Description

When trying to run the app using an executable jar I get ClassNotFoundException.

## How to reproduce

```
$ mvn clean package
[...]
$ java -jar target/tetris-0.1.jar 
Error: Could not find or load main class com.epam.prejap.git.tetris.Tetris
Caused by: java.lang.ClassNotFoundException: com.epam.prejap.git.tetris.Tetris
```

## Expected behavior

```
$ mvn clean package
[...]
$ java -jar target/tetris-0.1.jar
+--------------------+
|         ##         |
|         ##         |
|                    |
|                    |
|                    |
|                    |
|                    |
|                    |
|                    |
|                    |
+--------------------+
[...]

### PR DESCRIPTION
**Pull request by deetree**
Changed main class FQN in pom.xml, so the jar can be properly built
and launched.
Closes #21

### CODE REVIEW

**Review by pkierat-epam — CHANGES_REQUESTED** [review]
Where are tests that prove this task is working?

**Comment by deetree** [comment]
How can I check it? Run the jar through test code?

File: src/test/java/com/epam/prejap/teatrees/JarTest.java [hunk 1]
```diff
@@ -0,0 +1,59 @@
...
+import java.util.jar.Attributes;
+import java.util.jar.JarFile;
+
+/**
+ * Tests jar file
+ *
+ * @author Mariusz Bal
+ */
+@Test
+public class JarTest {
```
Comment (pkierat-epam) [inline src/test/java/com/epam/prejap/teatrees/JarTest.java:19]: Have you tried to run this as a part of Maven lifecycle? Since it's a regular test (no group, no IT, no maven-failsafe-plugin in the POM), it's gonna be executed in the "test" phase along with the rest of unit tests. But this test is definitely not a unit test, since it touches the filesystem.

Moreover, since it's executed in the test phase, and the jar is built in the "package" phase which is after the tests, the test will simply fail.

Try running this:
```
mvn clean verify
```

File: src/test/java/com/epam/prejap/teatrees/JarTest.java [hunk 2]
```diff
@@ -0,0 +1,59 @@
...
+     * Looks for the file of name starting with project name and having .jar extension
+     *
+     * @return the file if it meets naming requirements or {@code null} otherwise
+     */
+    private File getJarFile() {
+        File[] files = new File("target").listFiles();
+        return Arrays.stream(files)
+                .filter(f -> f.getName().startsWith("tea-trees") && f.getName().endsWith(".jar"))
+                .findAny()
+                .orElse(null);
```
Comment (pkierat-epam) [inline src/test/java/com/epam/prejap/teatrees/JarTest.java:38]: So if there's no jar file, the method will return `null`, and this will cause the test below to throw NPE instead of failing...

**Review by pkierat-epam — CHANGES_REQUESTED** [review]

**Review by pkierat-epam — CHANGES_REQUESTED** [review]
Please bump up the version.

**Comment by deetree** [comment]
> Please bump up the version.

Done

**Review by pkierat-epam — APPROVED** [review]
Well done. To be merged during the lecture on Monday.

**Comment by marcin-ogorzalek-EPAM** [comment]
@deetree BTW with the approval you probably may work on another PR :P

File: pom.xml [hunk 3]
```diff
@@ -38,11 +38,27 @@
...
+                <artifactId>maven-failsafe-plugin</artifactId>
+                <version>3.0.0-M5</version>
+                <configuration>
+                    <groups>IT</groups>
+                </configuration>
+                <executions>
+                    <execution>
+                        <goals>
+                            <goal>integration-test</goal>
+                            <goal>verify</goal>
```
Comment (pkierat-epam) [inline pom.xml:57]: This is not necessary, since `integration-test` is executed prior to `verify`.

File: src/test/java/com/epam/prejap/teatrees/JarIT.java [hunk 4]
```diff
@@ -0,0 +1,69 @@
...
+    public void setup() {
+        file = getJarFile();
+    }
+
+    /**
+     * Checks whether the file retrieved is not null. Other tests depend on its result.
+     * They may proceed if this one success.
+     */
+    public void shouldFileNotBeNull() {
+        Assert.assertNotNull(file, "The file must not be null");
```
Comment (pkierat-epam) [inline src/test/java/com/epam/prejap/teatrees/JarIT.java:33]: `Assert` could be statically imported.

File: src/test/java/com/epam/prejap/teatrees/JarIT.java [hunk 5]
```diff
@@ -0,0 +1,69 @@
...
+     * Looks for the file of name starting with project name and having .jar extension
+     *
+     * @return the file if it meets naming requirements or {@code null} otherwise
+     */
+    private File getJarFile() {
+        File[] files = new File("target").listFiles();
+        return Arrays.stream(files)
+                .filter(f -> f.getName().startsWith("tea-trees") && f.getName().endsWith(".jar"))
+                .findAny()
+                .orElse(null);
```
Comment (pkierat-epam) [inline src/test/java/com/epam/prejap/teatrees/JarIT.java:46]: An exception could be thrown here instead of returning `null`.

File: src/test/java/com/epam/prejap/teatrees/JarIT.java [hunk 6]
```diff
@@ -0,0 +1,69 @@
...
+import java.util.jar.Attributes;
+import java.util.jar.JarFile;
+
+/**
+ * Tests jar file
+ *
+ * @author Mariusz Bal
+ */
+@Test(groups = "IT")
+public class JarIT {
```
Comment (pkierat-epam) [inline src/test/java/com/epam/prejap/teatrees/JarIT.java:19]: It would be nice to check if the jar can be executed.

**Review by pkierat-epam — APPROVED** [review]
Minor changes, not required for merge.
